services:
  code-server:
    image: ghcr.io/coder/code-server:latest
    entrypoint: /usr/local/bin/init.sh
    environment:
      PASSWORD: password
      DOCKER_USER: joe
    user: "1000:1000"
    ports:
      - "8080:8080"
    volumes:
      - ./init.sh:/usr/local/bin/init.sh
      - ./src/:/home/src/
      - coder:/home/coder
  accelerator-lab:
    build: ./src/
    image: camptocamp/openmetrics-accelerator-lab:latest
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 5678:5678
      - 5000:5000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/etc/grafana/dashboards/
    depends_on:
      - prometheus
    restart: unless-stopped
volumes:
  coder:
  grafana-data: