{
 "title": "Openmetrics Accelerator Lab",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Beam speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    { "expr": "max(beam_speed_km_s)", "legendFormat": "Beam Speed" },
    { "expr": "299792458", "legendFormat": "Speed of light" },
    {
     "expr": "(accelerator_state == 2) / 2 * 299792458",
     "legendFormat": "Success"
    },
    { "expr": "beam_energy_mev*1000000", "legendFormat": "Beam Energy" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "accelerator_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kick Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "kick_power", "legendFormat": "Kick Power" }
   ]
  }
 ]
}